version: '3.9'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo:/data/db

  api:
    build: .
    ports:
      - 3000:3000
    environment:
      - MONGOURL=mongodb://mongo:27017/short-url
    depends_on:
      - mongo
    volumes:
      - .:/usesr/url-app

volumes:
  mongo : {}
  