name: Node.js CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Pull Docker image
      run: docker pull balajisabbineni/urlshortner:v1.0

    - name: Run Docker Compose
      run: docker compose up -d

    - name: Wait for services to be ready
      run: sleep 10

    - name: Check Docker Compose logs for errors
      run: |
        docker compose logs --no-color > docker-compose-logs.txt
        if grep -i "error" docker-compose-logs.txt; then
          echo "Errors found in logs"
          exit 1
        fi

    - name: Upload Docker Compose logs
      uses: actions/upload-artifact@v3
      with:
        name: docker-compose-logs
        path: docker-compose-logs.txt

    - name: Stop Docker container
      run: docker compose down
